[package]
name = "f2c"
version = "0.1.0"
authors = ["Jordyn <jordyn@husk.pro>"]
edition = "2018"
repository = "https://github.com/Huskehhh/f2c"
description = "Reads the content of a file to clipboard"
license = "MIT"

[dependencies]
clipboard = "0.5.0"
clap = "2.33.3"
